### ISSUE TITLE
Promise-related crashes (pdf.js)

### ISSUE THREAD

**Issue by Matojeje** [dictadata/pdf-data-parser#1]
Hello, I tried running the CLI on multiple systems and no matter the input file, the output always looks something like this:

```
TypeError: Promise.withResolvers is not a function
    at new PDFDocumentLoadingTask (file:///home/pi/Downloads/node-v20.10.0-linux-armv6l/lib/node_modules/pdf-data-parser/node_modules/pdfjs-dist/build/pdf.mjs:2957:32)
    at Module.getDocument (file:///home/pi/Downloads/node-v20.10.0-linux-armv6l/lib/node_modules/pdf-data-parser/node_modules/pdfjs-dist/build/pdf.mjs:2771:16)
    at PdfDataParser.parse (/home/pi/Downloads/node-v20.10.0-linux-armv6l/lib/node_modules/pdf-data-parser/lib/PdfDataParser.js:75:34)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Promise.withResolvers is not a function
    at new PDFDocumentLoadingTask (file:///home/pi/Downloads/node-v20.10.0-linux-armv6l/lib/node_modules/pdf-data-parser/node_modules/pdfjs-dist/build/pdf.mjs:2957:32)
    at Module.getDocument (file:///home/pi/Downloads/node-v20.10.0-linux-armv6l/lib/node_modules/pdf-data-parser/node_modules/pdfjs-dist/build/pdf.mjs:2771:16)
    at PdfDataParser.parse (/home/pi/Downloads/node-v20.10.0-linux-armv6l/lib/node_modules/pdf-data-parser/lib/PdfDataParser.js:75:34)

Node.js v20.10.0

```

Running this on different Node versions or operating systems would only change the displayed filepaths somewhat, but the stack trace stays the same.

The problem seems to be upstream in the pdf.js library (namely [this](https://github.com/mozilla/pdf.js/blob/7290faf840ab5a3828d12bbbb460bd8ad49f6ffa/src/display/api.js#L579) bit of code), where [this pull request](https://github.com/mozilla/pdf.js/pull/17854) created [this issue](https://github.com/mozilla/pdf.js/issues/17932).

I temporarily got around it by manually editing pdf-data-parser's `package.json` to require an earlier version than `pdfjs-dist@4.1.392` where this issue started to appear.

**Comment by drewletcher** [comment]
Fixed the issue by using the legacy version of pdf.js.

In lib/PdfDataParser.js:

```javascript
      const { getDocument } = await import("pdfjs-dist/legacy/build/pdf.mjs");     
```

Odd that it was working when testing on Windows 11, but when I installed the package on Rocky Linux I ran into the same issue with Node.js not supporting Promise.withResolvers, yet.

Published _pdf-data-parser 1.2.9_ with the fix.
